on: 
  push:
    branches:
      - test_actions
    paths:
      - 'UI/CarDB-React/**'
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    environment: CarDB
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      
    - name: 🔨 Build Project
      working-directory: UI/CarDB-React
      run: |
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server: ${{ secrets.FTP_SERVER }}
        dry-run: true
        protocol: ftps
        local-dir: UI/CarDB-React/build/
        server-dir: ${{ secrets.REACT_SERVER_DIR }}
